name: setup Homebrew test

on: 
  workflow_dispatch:

jobs:
  main: 
    runs-on: macos-15
    steps:
      - name: setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: false
          debug: true
